module.exports = [{
    id:1,
    date: '2016-05-01',
    name: 'Tom1',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    tag: 'Home',
},
{
    id:2,
    date: '2016-05-02',
    name: 'Tom2',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    tag: 'Office',
},
{
    id:3,
    date: '2016-05-03',
    name: 'Tom3',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    tag: 'Home',
},
{
    id:4,
    date: '2016-05-04',
    name: 'Tom4',
    state: 'California',
    city: 'Los Angeles',
    address: 'No. 189, Grove St, Los Angeles',
    tag: 'Office',
}]